services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

#  app:
#    container_name: app
#    image: beassignment
#    network_mode: host
#    environment:
#      NODE_ENV: production
#    build:
#      dockerfile: Dockerfile
#      context: .
#    ports:
#      - "9000:9000"
#    depends_on:
#      db:
#        condition: service_healthy

volumes:
  postgres: